### ISSUE TITLE
[Linux] Pictures not shown for PC games with files .PIC

### ISSUE THREAD

**Issue by cibersheep** [DavidKinder/Level9#10]
I've tested 
- Knight Orc
- Gnome Ranger
- Ingrid's Back

If picture files are named with uppercase .PIC, they will not show.

Tested with gtk and glk implementations.

Workaround: rename files to lowecase .pic

**Comment by DavidKinder** [comment]
Addressed by commit b5c2419de163af52506f6e9ef0122159fd6ce947
