### ISSUE TITLE
Any game with 3 parts «packed» will play only last one

### ISSUE THREAD

**Issue by cibersheep** [DavidKinder/Level9#11]
Atari disk images (.atr) and tared games (.tar) of games with 3 parts (Jewels of the Darkness, Knight Orc, etc) will start last part

**Comment by DavidKinder** [comment]
That is what I would expect. The interpreter knows nothing of the structure of these formats, so just scans the raw bytes looking for blocks of data that look like it's a Level 9 game file. Which it comes across first will just depend on how the data is laid out.

**Comment by cibersheep** [comment]
Oh, I would expect to play first the first part which has a way to chose what part to play instead of the last one.
