### ISSUE TITLE
Gtk source code doesn't compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by cibersheep** [DavidKinder/Level9#2]
It's fairly easy to update the configuration to make it compile.

1) Make sure libgtk2.0-dev are installed on your system.
`sudo apt install libgtk2.0-dev`

2) The compiler gives an error after trying to compile with `make`
```
gcc -o gtklevel9 level9.o bitmap.o main.o config.o gui.o text.o graphics.o util.o `pkg-config --libs gtk+-2.0`
/usr/bin/ld: bitmap.o: referencia sin definir al símbolo 'pow@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:46: fallo en las instrucciones para el objetivo 'gtklevel9'
make: *** [gtklevel9] Error 1
```
Just edit the *Makefile* file in /gtk [on line 43](https://github.com/DavidKinder/Level9/blob/master/Gtk/Makefile#L43): adding `-lm` flag (to include math library:

`LIBS = $(GTK_LIBS) -lm`

3) Run `make` in the /gtk folder

**Comment by DavidKinder** [comment]
"-lm" added to Gtk Makefile as per the above suggestion.
