### ISSUE TITLE
Graphics / Line drawings seems not to work with glk implementation

### ISSUE THREAD

**Issue by cibersheep** [DavidKinder/Level9#3]
I have compiled glk implementation with cheapglk and remglk.
- Checked that the game I'm playing has graphics (in garglk pictures are shown).
- In remglk: after initiate with `{ "type": "init", "gen": 0, "metrics": { "width":800, "height":600 },  "support": [ "graphics", "graphicswin" ] }` and typing `glk graphics` I get «Glk graphics are not available.»
- In cheapglk, typing `glk graphics` also shows: «Glk graphics are not available.»

**Comment by cibersheep** [comment]
Building level9 glk with cheapglk outputs:
```
$ make -f Makefile.glk glklevel9 
cp ../level9.c level9.c
cp ../level9.h level9.h
gcc -fPIC -ansi -I../../cheapglk -Wall   -O2 -DBITMAP_DECODER 						\
	-DNEED_STRICMP_PROTOTYPE -Dstricmp=gln_strcasecmp	\
	-Dstrnicmp=gln_strncasecmp -c -o level9.o level9.c
level9.c:159:1: warning: missing braces around initializer [-Wmissing-braces]
 {
 ^
level9.c:159:1: note: (near initialization for ‘L9V1Games’)
level9.c: In function ‘ScanV1’:
level9.c:1201:18: warning: variable ‘MaxJK’ set but not used [-Wunused-but-set-variable]
  L9BOOL JumpKill,MaxJK;
                  ^
level9.c:1200:26: warning: variable ‘MaxMax’ set but not used [-Wunused-but-set-variable]
  L9UINT32 Min,Max,MaxMin,MaxMax;
                          ^
level9.c:1200:19: warning: variable ‘MaxMin’ set but not used [-Wunused-but-set-variable]
  L9UINT32 Min,Max,MaxMin,MaxMax;
                   ^
level9.c: In function ‘corruptinginput’:
level9.c:2480:15: warning: variable ‘keywordnumber’ set but not used [-Wunused-but-set-variable]
  int d0,d1,d2,keywordnumber,abrevword;
               ^
level9.c: In function ‘listhandler’:
level9.c:3741:17: warning: suggest parentheses around ‘+’ in operand of ‘&’ [-Wparentheses]
  a4=L9Pointers[1+code&0x1f];
                 ^
level9.c: In function ‘intinitialise’:
level9.c:1509:8: warning: iteration 5u invokes undefined behavior [-Waggressive-loop-optimizations]
    int off=L9V1Games[L9V1Game].L9Ptrs[i];
        ^
level9.c:1507:3: note: containing loop
   for (i=0;i<6;i++)
   ^
level9.c: In function ‘ScanV1’:
level9.c:1256:8: warning: ‘dictOff1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  for (i=dictOff1;i<FileSize-20;i++)
        ^
cp ../bitmap.c bitmap.c
gcc -fPIC -ansi -I../../cheapglk -Wall   -O2 -DBITMAP_DECODER 						\
	-DNEED_STRICMP_PROTOTYPE -Dstricmp=gln_strcasecmp	\
	-Dstrnicmp=gln_strncasecmp -c -o bitmap.o bitmap.c
bitmap.c: In function ‘DecodeBitmap’:
bitmap.c:1519:2: warning: enumeration value ‘NO_BITMAPS’ not handled in switch [-Wswitch]
  switch (type)
  ^
bitmap.c: In function ‘bitmap_c64_decode’:
bitmap.c:1328:8: warning: ‘col_comp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     if (col_comp)
        ^
bitmap.c:1319:13: warning: ‘off_bg’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     i = data[off_bg] & 0x0f;
             ^
bitmap.c:1331:22: warning: ‘off_col’ may be used uninitialized in this function [-Wmaybe-uninitialized]
      i = data[off_col+(cy*40+cx)] & 0x0f;
                      ^
bitmap.c:1325:21: warning: ‘off_scr’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     i = data[off_scr+cy*40+cx] & 0x0f;
                     ^
bitmap.c:1313:16: warning: ‘off’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    p = data[off+(cy*40+cx)*8+py];
                ^
bitmap.c:1304:2: warning: ‘max_y’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  for (yi = 0; yi < max_y; yi++)
  ^
gcc -fPIC -ansi -I../../cheapglk -Wall   -O2 -DBITMAP_DECODER   -c -o glk.o glk.c
glk.c: In function ‘os_save_file’:
glk.c:5889:34: warning: pointer targets in passing argument 2 of ‘glk_put_buffer_stream’ differ in signedness [-Wpointer-sign]
   glk_put_buffer_stream (stream, ptr, bytes);
                                  ^
In file included from glk.c:50:0:
../../remglk/glk.h:255:13: note: expected ‘char *’ but argument is of type ‘gln_byte * {aka unsigned char *}’
 extern void glk_put_buffer_stream(strid_t str, char *buf, glui32 len);
             ^
glk.c: In function ‘os_load_file’:
glk.c:5936:43: warning: pointer targets in passing argument 2 of ‘glk_get_buffer_stream’ differ in signedness [-Wpointer-sign]
   *bytes = glk_get_buffer_stream (stream, ptr, max);
                                           ^
In file included from glk.c:50:0:
../../remglk/glk.h:261:15: note: expected ‘char *’ but argument is of type ‘gln_byte * {aka unsigned char *}’
 extern glui32 glk_get_buffer_stream(strid_t str, char *buf, glui32 len);
               ^
glk.c: At top level:
glk.c:2151:1: warning: ‘gln_graphics_paint_everything’ defined but not used [-Wunused-function]
 gln_graphics_paint_everything (winid_t glk_window,
 ^
gcc  -o glklevel9 level9.o bitmap.o glk.o  -lm -L../../cheapglk -lcheapglk			\
	-Wl,--wrap,toupper,--wrap,tolower
../../cheapglk/libcheapglk.a(cgfref.o): In funtion `glk_fileref_create_temp':
[...]/glk/terps/cheapglk/cgfref.c:111: Warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'

```

**Comment by DavidKinder** [comment]
"Glk graphics are not available." is printed if the Glk library doesn't report that it supports both graphics and timers - see the code in Glk/glk.c.

**Comment by cibersheep** [comment]
Thanks and sorry

**Comment by cibersheep** [comment]
Sorry to bother you again with this but:
I managed to make remglk to open a graphicswin but with empty content ("content" only contents text buffer).
If I `glk graphics` looks that the line art is rendered (because we get picture size?) but I don't know how to get the bitmap info nor where is it stored.
```
Glk graphics are available, and enabled.
There is a picture loaded, 160 by 96 pixels.
Graphics are active, 32 colours.
```
I have read again glk.c and I'm lost.
I'm doing something wrong? Or remglk doesn't support this kind of graphics?

**Comment by DavidKinder** [comment]
I don't know the code in glk.c well, as it was contributed by Simon Baldwin. And I don't know what exactly remglk supports either, sorry.

**Comment by cibersheep** [comment]
Do not worry. Thanks for your time

**Comment by DavidKinder** [comment]
I've had a brief look at the code in glk.c. It's not doing anything that I can see that's outside of the rules of what's allowed by the Glk specification, so as far as I can see, if RemGlk says that it supports graphics and timers, then it ought, at least in principle, to work. I guess that doesn't help much - you'll have to debug it I guess.

**Comment by cibersheep** [comment]
Thanks again to take time to look into it. I appreciate it.

Just «for the log»:
I know the code works with gargoyle / garglk so we must «blame» me or remglk :)
Remglk in other implementations (glulx for example) it gives an image number that correlates with the image of the room / state in the blorb file. So it might be that remglk expects the image as a local file.
If I understand correctly glklevel9 renders the line art «plotting» it into a bitmap. But I don't know where is stored.
My guess is that:
- I might have to tell remglk to show the image. I tried to do a refresh with no luck. I have to find out if there's a graphic stream I have to pull the bitmap from.
- Or that remglk expects me to take care of the image (and find it «locally»). But I cannot find any reference to it.

I'm puzzled because I know the line art is handled by a «trick» (this plotting into an bitmap) but with Scapeghost for example, I expected to get the image information as it would work very similar to a resource in a gblorb.
If `glk graphics` says the image is ready we should believe it :)

Let's see if I can discover something.
Thanks again

**Comment by cibersheep** [comment]
Update. Following with «the log».
I got something (that is a bit puzzling as well but I feel we are closer).
1) loaded snowball.sna (spectrum version) in remglk
2) I did the first action to have an image
3) Triggered the timer? (I learnt a new trick): with `{ "type":"timer", "gen":2 }` (generation 2 because on generation 1 I did the game action)
and got the ¿line art? (it should be the open coffin)
```
{ "type":"timer", "gen":2 }
{"type":"update", "gen":3,
 "content":[
 {"id":23, "draw": [
{"special":"setcolor", "color":"#FFFFFF"},
{"special":"fill"},
{"special":"fill", "x":819, "y":176, "width":164, "height":100, "color":"#000000"},
{"special":"fill", "x":981, "y":176, "width":2, "height":1, "color":"#FFFFFF"},
{"special":"fill", "x":819, "y":274, "width":1, "height":2, "color":"#FFFFFF"},
{"special":"fill", "x":981, "y":177, "width":2, "height":1, "color":"#E0E0E0"},
{"special":"fill", "x":820, "y":274, "width":1, "height":2, "color":"#E0E0E0"},
{"special":"fill", "x":981, "y":178, "width":2, "height":1, "color":"#C1C1C1"},
{"special":"fill", "x":821, "y":274, "width":1, "height":2, "color":"#C1C1C1"},
{"special":"fill", "x":981, "y":179, "width":2, "height":1, "color":"#A2A2A2"},
{"special":"fill", "x":822, "y":274, "width":1, "height":2, "color":"#A2A2A2"},
{"special":"fill", "x":981, "y":180, "width":2, "height":1, "color":"#838383"},
{"special":"fill", "x":823, "y":274, "width":1, "height":2, "color":"#838383"},
[...]
{"special":"fill", "x":879, "y":250, "width":37, "height":1, "color":"#43CD80"},
{"special":"fill", "x":879, "y":250, "width":36, "height":2, "color":"#43CD80"},
{"special":"fill", "x":922, "y":251, "width":58, "height":4, "color":"#43CD80"},
{"special":"fill", "x":878, "y":252, "width":36, "height":2, "color":"#43CD80"},
{"special":"fill", "x":921, "y":252, "width":59, "height":3, "color":"#43CD80"},
{"special":"fill", "x":877, "y":253, "width":37, "height":1, "color":"#43CD80"},
{"special":"fill", "x":876, "y":254, "width":37, "height":1, "color":"#43CD80"},
{"special":"fill", "x":920, "y":254, "width":60, "height":1, "color":"#43CD80"}
 ] }
 ],
 "input":[
 {"id":20, "gen":2, "type":"line", "maxlen":499 }
 ],
 "timer":null}
```

**Comment by cibersheep** [comment]
¿Why I'm puzzled? Because if I load Scapeghost I get also line art information. I'll keep investigating.
Edit: All is working good. So, in Scapeghost is using also a sort of «line art» to draw the image.
I did a quick test with the info received. I draw in an html5 canvas. It's not finished but we are there.

Make sure to do a timer update until you get "timer":null
![imatge](https://user-images.githubusercontent.com/6640041/36512514-0bfe43f0-176b-11e8-9d68-7f9dad1c1474.png)

**Comment by DavidKinder** [comment]
That makes sense. The code in glk.c builds up a bitmap from either the line art instructions, or from the bitmap image loaded by the game, but in either case it has to send that to the front-end with Glk calls. Glk's graphics support is pretty limited - basically all you can do is draw rectangles in a given colour. So the code in Glk.c converts the local bitmap it has into Glk calls that draw parts of the image as rectangles, and that's what gets set to the front-end. So from RemGlk's point of view, both the line art images and bitmap images come through as Glk graphics windows calls.

**Comment by cibersheep** [comment]
It's pretty clever. Even if limited, it makes possible to have the images in a json (in this case).
Thanks again for your time. I hope I can give some of mine to you. I'm in debt with you
