### ISSUE TITLE
Is extracting all location images possible?

### ISSUE THREAD

**Issue by RichyH67** [DavidKinder/Level9#4]
Hope this is the right place to ask, but is it possible to extract all of the location images from (for example) the C64 versions of Level 9 games somehow (specifically v2 and v3 games)? Obviously, it is possible to do this by playing through the entire game and saving a screenshot at each location, but I was wondering if the tools already exist to be able to do this? I'm not a programmer, so am assuming that the repeated objects are stored as lines and fills (seeing as they are constructed on the screen as you watch). Not that it is relevant, but I used to work at Rainbird Software and we published some of these titles (but this was just before my time at the company!). Thanks!

**Comment by DavidKinder** [comment]
In the interpreter, you can use the meta-command "#picture <n>" (e.g. "#picture 300") to run the graphics routines for a particular picture number, but not all of them are actual pictures (some are sub-routines for parts of pictures). As you say, they're stored as sets of instructions for lines and fills, basically, but it's not easy to tell where the routines for a specific location (or even any location) start.

**Comment by RichyH67** [comment]
I'm actually interested in how the pictures build up, so this looks like it will help! :-)
