### ISSUE TITLE
Play games from compressed Z80 Spectrum memory snapshots

### ISSUE THREAD

**Issue by DavidKinder** [DavidKinder/Level9#7]
Decompressing Z80 files is not particularly difficult, see the l9cut source code (https://ifarchive.org/indexes/if-archive/level9/tools/).

**Comment by cibersheep** [comment]
That's interesting.
A bit tangent but:
- I have tried to tar v3? (ie PC files: SNOWBALL.DAT SNOWBALL.CGA SNOWBALL.HRC) and they work as a whole, the terp finds the image files.
- I have tried the same with v4? (ie PC files from ScapeGhost: GAMEDAT1.DAT + all the images files) but that didn't work.

I think we have this before somewhere but would it be doable to support a tar/blorb/? file for games with multiple files?

**Comment by DavidKinder** [comment]
That behavior with tar files makes sense, as tar does not compress files, unless you tell it to pass them to gzip or bzip2. Using Blorb files is certainly possible but that is a different, and more complex, issue, as that would also require a utility to create such files.

**Comment by cibersheep** [comment]
Indeed, tar makes a lot of sense (at least for me) as it is easy to create as a user.
Do you think is a bug that doesn't work with modern games?

**Comment by DavidKinder** [comment]
No, I don't think that that is a bug. The interpreter has no way to detect all the parts of a multi-part game file in a block of memory, or to detect bitmap graphics files, and it's probably impossible to change it to do so in a completely generic way.

**Comment by cibersheep** [comment]
I see. Thanks for the time and sorry for the noise ;)

**Comment by DavidKinder** [comment]
I have written up using Blorb files as https://github.com/DavidKinder/Level9/issues/8. When (or even whether) I'll ever get round to it I can't say, but it seems at least worth recording the idea.

**Comment by DavidKinder** [comment]
In retrospect, I don't think teaching the interpreter about .Z80 snapshots is the way to go. Much better is the idea to support Blorb files, along with a tool to generate them, so I am closing this issue.
