### ISSUE TITLE
Add a menu item to set the background colour

### ISSUE THREAD

**Issue by ash73** [DavidKinder/Level9#9]
Hi David, I enjoy using your magnetic scrolls, infocom and level 9 emulators - any chance of adding a background text colour option to the Level 9 emulator? Currently you can only change the font foreground colour, and my eyesight is struggling a bit with the white background - I use white text on a dark grey background in the other two.

**Comment by DavidKinder** [comment]
This seems like a sensible thing to do, I'll add it when I next do some more work on the interpreter.

**Comment by steve-arnold** [comment]
I have made a PR with added background colour selection in the Windows options menu.

**Comment by DavidKinder** [comment]
Implemented in commit d25fd38b744fe54bf309aecddfceeddfe8ad5785, which is a slightly modified version of this PR: https://github.com/DavidKinder/Level9/pull/14
